---
- hosts: localhost
  become: true
  connection: local
  vars:
  roles:
  tasks:
    - name: install curator crontab
      cron:
        name: "es_curator_delete"
        special_time: "daily"
        user: "www-data"
        job: '/usr/local/bin/curator --host {{ elasticsearch_host }} delete indices --time-unit days --timestring "\%Y.\%m.\%d" --older-than {{ delete_older_than_in_days | default(360) }}'
        cron_file: "es_curator_delete"
        state: "present"
